<?php
echo "<!DOCTYPE html>\n"; 
echo "<html lang=\"en\">\n"; 
echo "\n"; 
echo "<head>\n"; 
echo "\n"; 
echo "    <meta charset=\"utf-8\">\n"; 
echo "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"; 
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"; 
echo "    <meta name=\"description\" content=\"website film SuperNova\">\n"; 
echo "    <meta name=\"author\" content=\"Yoevi Sanjaya\">\n"; 
echo "\n"; 
echo "    <title>Film Supernova</title>\n"; 
echo "\n"; 
echo "    <!-- Bootstrap Core CSS -->\n"; 
echo "    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\n"; 
echo "\n"; 
echo "    <!-- Custom CSS -->\n"; 
echo "    <link href=\"css/grayscale.css\" rel=\"stylesheet\">\n"; 
echo "	<link href=\"css/add.css\" rel=\"stylesheet\">\n"; 
echo "	<!--<link href=\"css/animate.css\" rel=\"stylesheet\"> -->\n"; 
echo "\n"; 
echo "    <!-- Custom Fonts -->\n"; 
echo "    <link href=\"font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\"><!--\n"; 
echo "    <link href=\"http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic\" rel=\"stylesheet\" type=\"text/css\">\n"; 
echo "    <link href=\"http://fonts.googleapis.com/css?family=Montserrat:400,700\" rel=\"stylesheet\" type=\"text/css\"> -->\n"; 
echo "\n"; 
echo "    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\n"; 
echo "    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n"; 
echo "    <!--[if lt IE 9]>\n"; 
echo "        <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\n"; 
echo "        <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\n"; 
echo "    <![endif]-->\n"; 
echo "\n"; 
echo "</head>\n"; 
echo "\n"; 
echo "<body id=\"page-top\" data-spy=\"scroll\" data-target=\".navbar-fixed-top\">\n"; 
echo "\n"; 
echo "<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-46225492-1', 'auto');
  ga('send', 'pageview');

</script>";
echo "    <!-- Navigation --><!--\n"; 
echo "    <nav class=\"navbar navbar-custom navbar-fixed-top\" role=\"navigation\">\n"; 
echo "        <div class=\"container\">\n"; 
echo "            <!--<div class=\"navbar-header\">\n"; 
echo "                <!--	<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-main-collapse\">\n"; 
echo "                    <i class=\"fa fa-bars\"></i>\n"; 
echo "                </button> -->\n"; 
echo "                <!--<a class=\"navbar-brand page-scroll\" href=\"#page-top\">\n"; 
echo "                    <span class=\"light\">Soraya Intercine Films</span>\n"; 
echo "                </a>\n"; 
echo "            </div>-->\n"; 
echo "\n"; 
echo "            <!-- Collect the nav links, forms, and other content for toggling -->\n"; 
echo "           <!-- <div class=\"collapse navbar-collapse navbar-right navbar-main-collapse\">\n"; 
echo "                <ul class=\"nav navbar-nav\">\n"; 
echo "                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->\n"; 
echo "                    <!--<li class=\"hidden\">\n"; 
echo "                        <a href=\"#page-top\"></a>\n"; 
echo "                    </li>\n"; 
echo "                    <li>\n"; 
echo "                        <a class=\"page-scroll\" href=\"#about\">About</a>\n"; 
echo "                    </li>\n"; 
echo "                    <li>\n"; 
echo "                        <a class=\"page-scroll\" href=\"#download\">Download</a>\n"; 
echo "                    </li>\n"; 
echo "                    <li>\n"; 
echo "                        <a class=\"page-scroll\" href=\"#contact\">Contact</a>\n"; 
echo "                    </li>\n"; 
echo "                </ul>\n"; 
echo "            </div>-->\n"; 
echo "            <!-- /.navbar-collapse \n"; 
echo "        </div>\n"; 
echo "        <!-- /.container \n"; 
echo "    </nav>-->\n"; 
echo "\n"; 
echo "    <!-- Intro Header -->\n"; 
echo "    <header class=\"intro\">\n"; 
echo "        <div class=\"intro-body\">\n"; 
echo "            <div class=\"container\">\n"; 
echo "                <div class=\"row\">\n"; 
echo "                    <div class=\"col-md-8 col-md-offset-2\">\n"; 
echo "						<div class=\"embed-responsive embed-responsive-16by9\">\n"; 
echo "							<iframe src=\"//www.youtube.com/embed/FOUHtX90Jgc?rel=0&amp;showinfo=0\" frameborder=\"0\" allowfullscreen></iframe>\n"; 
echo "						</div>\n"; 
echo "						<div class=\"space\"></div>\n"; 
echo "                        <a href=\"#about\" class=\"btn btn-circle page-scroll\">\n"; 
echo "                            <i class=\"fa fa-angle-double-down animated\"></i>\n"; 
echo "                        </a>\n"; 
echo "                    </div>\n"; 
echo "					\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </header>\n"; 
echo "\n"; 
echo "    <!-- About Section -->\n"; 
echo "   <!-- <section id=\"about\" class=\"container content-section\"> -->\n"; 
echo "   <div class=\"container-fluid\">\n"; 
echo "	<section id=\"about\" class=\"page2\">\n"; 
echo "        <div class=\"row\">\n"; 
echo "            <div class=\"col-md-6\">\n"; 
echo "				<div class=\"panel panel-default\">\n"; 
echo "				  <div class=\"panel-body vertical-center\">\n"; 
echo "					<div role=\"tabpanel\">\n"; 
echo "						\n"; 
echo "						<div class=\"tab-content\">\n"; 
echo "							<div id=\"sectionA\" class=\"tab-pane fade in active\"><h5>Sinopsis</h5>\n"; 
echo "								<p class=\"text-justify\">Menunaikan ikrar mereka untuk berkarya bersama, pasangan Dimas dan Reuben mulai menulis roman yang diberi judul Kesatria, Putri, dan Bintang Jatuh. Paralel dengan itu, dalam kehidupan nyata, sebuah kisah cinta terlarang terjalin antara Ferre dan Rana. Hubungan cinta mereka merepresentasikan dinamika yang terjadi antara tokoh Kesatria dan Putri dalam fiksi Dimas dan Reuben. Tokoh ketiga, Bintang Jatuh, dihadirkan oleh seorang peragawati terkenal bernama Diva, yang memiliki profesi sampingan sebagai pelacur kelas atas.\n"; 
echo "</p>\n"; 
echo "							</div>\n"; 
echo "							<div id=\"sectionB\" class=\"tab-pane fade\"><h5>Sinopsis</h5>\n"; 
echo "								<p>Washington, D.C. Reuben and Dimas, two Indonesian students studying in the U.S., are brought together by the soft trance music echoing through a party at a mansion. That night they make a pact  one day they will write a book, a science fiction romance that will move the heart of the masses. The tale of the Knight, the Princess and the Shooting Star.\n"; 
echo "Jakarta. At an executive office, an impromptu interview between Ferre and Rana,  the former a young, affluent, brilliant and well-known executive, the other the Vice Editor in Chief of a top Indonesian women's magazine – changes the course of both their lives. A rare honest interview on love, sacrifice and freedom. A sweet interchange filled with pounding hearts and piercing gaze, a gaze too deep for Ferre and Rana. They fall in love.\n"; 
echo "Rana is married to Arwin, an entrepreneur from a renowned and distinguished family in Jakarta. The man Rana has chosen after the encouragement of her whole extended family,  that Rana is fortunate to marry Arwin and that Arwin is a man worthy as a husband and a source of pride, chosen by the family.\n"; 
echo "Ferre and Rana's beautiful story continues to unfold deeper, just like the Knight and the Princess in the kingdom of love. Both are drunk in a love they have never felt before. Ferre and Rana cannot break free from the chaos of forbidden love that feels right and the order of the private married life of Rana and Arwin, one that is acceptable but which feels wrong.\n"; 
echo "Diva, a top supermodel suddenly appears in Ferre's life. Through all the chaos and order of the universe, under the starry night and the flash of a shooting star, Diva arrives. Extraordinarily, it turns out that Diva lives in the same residential area as Ferre. Their houses even face each other.\n"; 
echo "Reuben, Dimas, Ferre, Rana, Arwin and Diva eventually meet without recognizing each other in an aggressive, poetic, romantic and phenomenal blog called \"Supernova\".\n"; 
echo "\n"; 
echo "Their stories erupt together with Supernova.\n"; 
echo "</p>\n"; 
echo "							</div>\n"; 
echo "							\n"; 
echo "								\n"; 
echo "						</div>\n"; 
echo "                       \n"; 
echo "                        <ul class=\"nav nav-tabs\">\n"; 
echo "							<li class=\"active\"><a data-toggle=\"tab\" href=\"#sectionA\">Bahasa</a></li>\n"; 
echo "							<li><a data-toggle=\"tab\" href=\"#sectionB\">English</a></li>	\n"; 
echo "						</ul>\n"; 
echo "					</div>\n"; 
echo "				  </div>\n"; 
echo "				</div>   \n"; 
echo "<div id=\"fb-root\"></div> \n"; 


 
 
echo "							<div id=\"sectionC\">\n"; 
echo "								<div class=\"tab-pane fb-comments\" data-href=\"http://sorayafilms.com/reborn/film_supernova.php\" data-width=\"100%\" data-numposts=\"5\" data-colorscheme=\"dark\"></div>					\n"; 
echo "							</div>				\n"; 
echo "            </div>\n"; 
echo "			<div class=\"col-md-6\">\n"; 
echo "                <img class=\"img-responsive center-block\" src=\"../../images/Supernova400.jpg\" alt=\"EXEMPLE\">\n"; 
echo "            </div>\n"; 
echo "			<!--\n"; 
echo "                        <a href=\"#comme\" class=\"btn btn-circle page-scroll\">\n"; 
echo "                            <i class=\"fa fa-angle-double-down animated\"></i>\n"; 
echo "                        </a> -->\n"; 
echo "        </div>\n"; 
echo "		\n"; 
echo "    </section>\n"; 
echo "      \n"; 
echo "	</div>\n"; 
echo "	\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "    <!-- Contact Section --><!--\n"; 
echo "    <section id=\"contact\" class=\"container content-section text-center\">\n"; 
echo "        <div class=\"row\">\n"; 
echo "            <div class=\"col-lg-8 col-lg-offset-2\">\n"; 
echo "                <h2>Contact Start Bootstrap</h2>\n"; 
echo "                <p>Feel free to email us to provide some feedback on our templates, give us suggestions for new templates and themes, or to just say hello!</p>\n"; 
echo "                <p><a href=\"mailto:feedback@startbootstrap.com\">feedback@startbootstrap.com</a>\n"; 
echo "                </p>\n"; 
echo "                <ul class=\"list-inline banner-social-buttons\">\n"; 
echo "                    <li>\n"; 
echo "                        <a href=\"https://twitter.com/SBootstrap\" class=\"btn btn-default btn-lg\"><i class=\"fa fa-twitter fa-fw\"></i> <span class=\"network-name\">Twitter</span></a>\n"; 
echo "                    </li>\n"; 
echo "                    <li>\n"; 
echo "                        <a href=\"https://github.com/IronSummitMedia/startbootstrap\" class=\"btn btn-default btn-lg\"><i class=\"fa fa-github fa-fw\"></i> <span class=\"network-name\">Github</span></a>\n"; 
echo "                    </li>\n"; 
echo "                    <li>\n"; 
echo "                        <a href=\"https://plus.google.com/+Startbootstrap/posts\" class=\"btn btn-default btn-lg\"><i class=\"fa fa-google-plus fa-fw\"></i> <span class=\"network-name\">Google+</span></a>\n"; 
echo "                    </li>\n"; 
echo "                </ul>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </section>-->\n"; 
echo "\n"; 
echo " \n"; 
echo "\n"; 
echo "    <!-- Footer --><!--\n"; 
echo "    <footer>\n"; 
echo "        <div class=\"container text-center\">\n"; 
echo "            <p>Copyright &copy; Your Website 2014</p>\n"; 
echo "        </div>\n"; 
echo "    </footer>-->\n"; 
echo "     \n"; 
echo "\n"; 
echo "\n"; 
echo "    <!-- jQuery -->\n"; 
echo "    <script src=\"js/jquery.js\"></script>\n"; 
echo "\n"; 
echo "    <!-- Bootstrap Core JavaScript -->\n"; 
echo "    <script src=\"js/bootstrap.min.js\"></script>\n"; 
echo "\n"; 
echo "    <!-- Plugin JavaScript -->\n"; 
echo "    <script src=\"js/jquery.easing.min.js\"></script>\n"; 
echo "\n"; 
echo "    <!-- Google Maps API Key - Use your own API key to enable the map feature. More information on the Google Maps API can be found at https://developers.google.com/maps/ -->\n"; 
echo "    <script type=\"text/javascript\" src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyCRngKslUGJTlibkQ3FkfTxj3Xss1UlZDA&sensor=false\"></script>\n"; 
echo "\n"; 
echo "    <!-- Custom Theme JavaScript -->\n"; 
echo "    <script src=\"js/grayscale.js\"></script>\n"; 
echo "	\n"; 
echo "	<div class=\"container\">\n"; 
echo "		<div class=\"row\">\n"; 
echo "			<div class=\"col-md-12\">\n"; 
echo "				<a href=\"http://www.sorayafilms.com\"><p class=\"text-center\">Home</p></a>\n"; 
echo "			</div>\n"; 
echo "		</div>\n"; 
echo "	</div>\n"; 
echo "\n"; 
echo "</body>\n"; 
echo "\n"; 
echo "</html>\n"; 
echo "\n";
?>
<?php
echo "<script>(function(d, s, id) {\n"; 
echo "  var js, fjs = d.getElementsByTagName(s)[0];\n"; 
echo "  if (d.getElementById(id)) return;\n"; 
echo "  js = d.createElement(s); js.id = id;\n"; 
echo "  js.src = \"//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=1551502481729302&version=v2.0\";\n"; 
echo "  fjs.parentNode.insertBefore(js, fjs);\n"; 
echo "}(document, 'script', 'facebook-jssdk'));\n"; 
echo "</script>\n";
?>